### ISSUE TITLE
获取播放信息

### ISSUE THREAD

**Issue by TrickeryJoker** [hamster1963/NextMe#1]
没找到在哪里修改实时获取播放信息。
用spotify要进行OAUTH验证，要多进行一步登录验证。请问博客里直接获取是怎么实现的？代码里没有看到这部分。

**Comment by hamster1963** [comment]
在nextjs中获取数据可以参考：
https://theodorusclarence.com/blog/spotify-now-playing
https://yidaotus.medium.com/building-a-dynamic-spotify-currently-playing-widget-with-typescript-react-and-next-js-c3a6ca5a9ff6
在我的博客[https://buycoffee.top]中是通过Go后端获取的,参考代码如下：
https://gist.github.com/hamster1963/3ceaf53a8582737a099d9ee6e623a8e7

**Comment by TrickeryJoker** [comment]
感谢 我学习一下
